export const YOUR_NAME = "Dr. Matthew Doyle";
export const YOUR_FIRST_NAME = "Matt"; // Or just "Matthew"
export const YOUR_TITLE = "Physicist & Developer";
export const HERO_SUBTITLE = "Building things and sharing knowledge";
export const ABOUT_ME_TEXT_1 = `Greetings! I'm ${YOUR_NAME}. With a strong foundation in analytical thinking and complex problem-solving from my scientific background, I'm passionate about both education and leveraging technology to create impactful digital experiences. My work spans from mentoring and teaching to developing modern, user-friendly websites and applications.`;
export const ABOUT_ME_TEXT_2 = `I thrive on breaking down complex concepts and making them accessible, whether in a classroom or through intuitive UI/UX design. I have a robust skillset in programming (including Python, JavaScript, and C++) and web technologies. I'm always eager to explore new challenges, collaborate on exciting projects, and help others achieve their learning and technological goals.`;

export const ABOUT_ME_DETAILED_PARAGRAPHS: string[] = [
  `My journey into the realms of physics and technology began with an insatiable curiosity about the universe and how things work. This led me to pursue a Ph.D. in Theoretical Physics, where I delved into the complexities of early universe cosmology and gravitational wave phenomenology. During this time, I honed my skills in analytical modeling, computational simulations, and rigorous data analysis. Working on projects such as N-body simulations of galaxy clusters and constraining inflationary parameters using CMB data taught me the importance of precision, perseverance, and innovative problem-solving.`,
  `Alongside my research, I discovered a profound passion for education and mentorship. Explaining intricate scientific concepts to students and seeing the spark of understanding in their eyes became incredibly rewarding. This passion extended to making complex ideas accessible through clear and engaging communication, a skill I find invaluable in both academic and technical fields.`,
  `Transitioning parts of my focus towards web development and technology felt like a natural extension of my analytical and problem-solving background. I found that the same principles of logical thinking, structured design, and iterative development that underpin scientific research are equally applicable to building robust and user-friendly software. I specialize in creating modern, responsive web applications using technologies like React, TypeScript, and Node.js, always aiming for clean code, intuitive user interfaces, and excellent performance.`,
  `My current work involves bridging these two worlds. I continue to engage with scientific research, particularly in areas where computation and data science play a crucial role. Simultaneously, I develop web solutions, from educational platforms to custom applications, that empower users and solve real-world problems. Whether it's unraveling the mysteries of the cosmos or crafting elegant code, my goal is to contribute meaningfully and make a positive impact.`,
  `I am always eager to learn, collaborate, and take on new challenges. If you have an interesting project, an idea to discuss, or simply want to connect, please don't hesitate to reach out!`
];

export const CONTACT_MESSAGE = "I am always open to discussing new ideas, collaborations, or opportunities. Please feel free to connect through the links below or send me a message.";
